services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      # - "14268"
      # - "14250"
    networks:
      - practical-otel-net  

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9412:9411"   
    networks:
      - practical-otel-net  