version: "3.9"

services:
    collector:
      image: otel/opentelemetry-collector-contrib:latest
      command: [ "--config=/etc/otel-collector.yaml" ]
      volumes:
        - ./config-files/otel-collector.yaml:/etc/otel-collector.yaml
      ports:
        # - 1888:1888 # pprof extension
        # - 13133:13133 # health_check extension
        # - 55679:55679 # zpages extension
        # - 8888:8888 # Prometheus metrics exposed by the collector
        # - 8889:8889 # Prometheus exporter metrics
        - 4317:4317 # OTLP gRPC receiver
        - 4318:4318 # OTLP http receiver
      depends_on:
        - jaeger
        - zipkin
        - prometheus
        - loki
      networks:
        - practical-otel-net  